version: "3.9"
services:
  db:
    image: postgres:16
    container_name: participa_df_db
    environment:
      POSTGRES_USER: participa
      POSTGRES_PASSWORD: participa
      POSTGRES_DB: participa_df
    ports:
      - "5432:5432"
    volumes:
      - participa_df_pgdata:/var/lib/postgresql/data
volumes:
  participa_df_pgdata:
